### ISSUE TITLE
Update @busveq for 8 highway time periods

### ISSUE THREAD

**Issue by tinleycraig** [CMAP-REPOS/mhn_programs#142]
The value in @busveq is used as background traffic in the volume-delay functions to determine total link volumes. Beginning with the ON TO 2050 Plan update, CMAP uses four time periods for transit assignment (NT: 6 pm – 6 am, AM: 6 am – 9 am, MD: 9 am – 4 pm, PM: 4 pm – 6 pm). The values for @busveq are added to the time-of-day highway networks by temporarily importing the transit coding from the appropriate transit time period and calculating the vehicle equivalents based on the headways of routes. However, the bus vehicle equivalents are being overestimated for every period except the PM peak because the transit assignment time periods don’t align with the traffic assignment periods except for the PM peak. An improved process would directly calculate @busveq from the bus coding in the MHN – this would ensure consistency with the traffic assignment periods (only capturing buses operating during the time period) and the value could be imported into the Emme networks as an extra link attribute.

**Comment by nrferguson** [comment]
See current processing in [initialize.scenarios](https://github.com/CMAP-REPOS/cmap_trip-based_model/blob/c23q4/Database/prep_macros/initialize.scenarios#L169). Add `@busveq` to the link extra attribute transaction files written in [generate_highways_files_2.sas](https://github.com/CMAP-REPOS/mhn_programs/blob/develop/src/generate_highway_files_2.sas#L456).

**Comment by tk-oleary** [comment]
this procedure is now completed within trip-based model run procedures in a combination of initialize_scenarios.py and TOD_network_skim.py
